import { createContext, useContext, useState, ReactNode } from "react";

type Language = "vi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  vi: {
    // Common
    "common.language": "vi",
    "common.previous": "Trước",
    "common.next": "Tiếp",
    "common.backHome": "Về trang chủ",
    "common.backToTournaments": "Về danh sách giải đấu",
    "common.share": "Chia sẻ",
    "common.availableOn": "Có sẵn trên",
    "common.getItOn": "Tải về từ",
    
    // Navigation
    "nav.home": "TRANG CHỦ",
    "nav.tournaments": "GIẢI ĐẤU",
    "nav.rankings": "BXH",
    "nav.players": "CƠ THỦ",
    "nav.clubs": "CÂU LẠC BỘ",
    "nav.news": "TIN TỨC",
    "nav.download": "TẢI ỨNG DỤNG",
    "nav.profile": "Hồ sơ",

    // App Download
    "app.getTheApp": "Tải Ứng Dụng",
    "app.betterExperience": "Trải nghiệm tốt hơn trên mobile",
    "app.downloadTitle": "Tải SABO Arena App",
    "app.downloadDescription": "Trải nghiệm bi-a tuyệt vời với ứng dụng mobile. Đăng ký giải đấu nhanh chóng, nhận thông báo trận đấu và kết nối với cộng đồng bi-a.",
    "app.feature1": "Đăng ký giải đấu trong 1 phút",
    "app.feature2": "Thông báo trận đấu real-time",
    "app.feature3": "Chat với đối thủ và bạn bè",

    // Footer
    "footer.description": "Nền tảng giải đấu bi-a hàng đầu Việt Nam. Kết nối cộng đồng, thi đấu chuyên nghiệp, nâng tầm kỹ năng.",
    "footer.quickLinks": "Liên kết nhanh",
    "footer.support": "Hỗ trợ",
    "footer.contact": "Liên hệ",
    "footer.liveMatches": "Trận đấu trực tiếp",
    "footer.privacy": "Chính sách bảo mật",
    "footer.terms": "Điều khoản dịch vụ",
    "footer.deleteAccount": "Xóa tài khoản",
    "footer.contactUs": "Liên hệ với chúng tôi",
    "footer.faq": "Câu hỏi thường gặp",
    "footer.address": "123 Đường ABC, Quận 1, TP.HCM, Việt Nam",
    "footer.allRightsReserved": "Tất cả quyền được bảo lưu.",
    "footer.madeWith": "Được tạo ra với",
    "footer.forBilliardCommunity": "cho cộng đồng bi-a Việt Nam",

    // Hero Section
    "hero.championship": "Giải Đấu",
    "hero.title1": "ĐẲNG CẤP",
    "hero.title2": "CHUYÊN NGHIỆP",
    "hero.title3": "CHỜ BẠN!",
    "hero.description": "Tham gia nền tảng giải đấu bi-a đẳng cấp. Thi đấu với những tay cơ xuất sắc, tham gia các giải đấu uy tín và nâng cao kỹ năng của bạn.",
    "hero.joinTournament": "ĐĂNG KÝ NGAY",
    "hero.viewRankings": "XEM BẢNG XẾP HẠNG",
    "hero.activePlayers": "Người Chơi",
    "hero.tournaments": "Giải Đấu",
    "hero.prizePool": "Giải Thưởng",
    "hero.scrollExplore": "Cuộn để khám phá",

    // Hero Cards
    "hero.upcomingTournament": "Giải Đấu Sắp Diễn Ra",
    "hero.proLeagueFinals": "Chung Kết Pro League 2024",
    "hero.tournamentDesc": "Đăng ký đóng trong 5 ngày. 64 người chơi tranh tài giải thưởng 50,000 USD.",
    "hero.joinNow": "TẢI APP NGAY",
    "hero.highlights": "Điểm Nổi Bật",
    "hero.topShots": "Những Cú Đánh Đỉnh Cao Tuần Này",
    "hero.topShotsDesc": "Xem những pha bóng đỉnh cao nhất từ giải đấu tuần này.",
    "hero.latestNews": "Tin Mới Nhất",
    "hero.championshipRules": "Công Bố Quy Định Giải Đấu Mới",
    "hero.rulesDesc": "Ban tổ chức giải đấu giới thiệu hệ thống tính điểm cập nhật cho mùa giải 2024.",
    "hero.readMore": "ĐỌC THÊM",

    // Tournaments
    "tournaments.upcoming": "GIẢI ĐẤU SẮP DIỄN RA",
    "tournaments.upcomingDescription": "Tham gia những giải đấu đẳng cấp quốc tế với những cơ thủ xuất sắc nhất",
    "tournaments.noUpcoming": "Hiện tại chưa có giải đấu nào sắp diễn ra",
    "tournaments.participants": "Người Tham Gia", 
    "tournaments.prize": "Giải Thưởng",
    "tournaments.entryFee": "Phí Tham Gia",
    "tournaments.register": "ĐĂNG KÝ",
    "tournaments.full": "ĐÃ ĐẦY",
    "tournaments.viewAll": "XEM TẤT CẢ",
    "tournaments.notFound": "Không tìm thấy giải đấu",
    "tournaments.notFoundDesc": "Giải đấu bạn tìm kiếm không tồn tại hoặc đã bị xóa",
    "tournaments.overview": "Tổng quan",
    "tournaments.bracket": "Bảng đấu",
    "tournaments.matches": "Trận đấu",
    "tournaments.participantsList": "Danh sách người tham gia",
    "tournaments.about": "Giới thiệu",
    "tournaments.format": "Hình thức",
    "tournaments.venue": "Địa điểm",
    "tournaments.startDate": "Ngày bắt đầu",
    "tournaments.endDate": "Ngày kết thúc",
    "tournaments.description": "Mô tả",
    "tournaments.rules": "Luật chơi",
    "tournaments.rule1": "Tất cả trận đấu phải được hoàn thành trong thời gian quy định",
    "tournaments.rule2": "Người chơi phải có mặt đúng giờ theo lịch trình",
    "tournaments.rule3": "Quyết định của trọng tài là quyết định cuối cùng",
    "tournaments.tournamentBracket": "Bảng đấu giải",
    "tournaments.bracketComingSoon": "Bảng đấu sẽ được cập nhật sớm",
    "tournaments.noBracket": "Chưa có bảng đấu",
    "tournaments.matchResults": "Kết quả trận đấu",
    "tournaments.noMatches": "Chưa có trận đấu nào",
    "tournaments.tbd": "Chưa xác định",
    "tournaments.scheduled": "Đã lên lịch",
    "tournaments.winner": "Người thắng",
    "tournaments.noParticipants": "Chưa có người tham gia",
    "tournaments.registration": "Đăng ký",
    "tournaments.spots": "Chỗ trống",
    "tournaments.organizer": "Ban tổ chức",
    "tournaments.quickStats": "Thống kê nhanh",
    "tournaments.avgRating": "Điểm TB",
    "tournaments.topSeed": "Hạt giống số 1",
    "tournaments.totalPrize": "Tổng giải thưởng",
    "tournaments.totalMatches": "Tổng trận đấu",
    "tournaments.prizePool": "Tiền thưởng",
    "tournaments.standard": "Chuẩn",
    "tournaments.status.upcoming": "Sắp diễn ra",
    "tournaments.status.ongoing": "Đang diễn ra",
    "tournaments.status.completed": "Đã kết thúc",
    "tournaments.status.cancelled": "Đã hủy",
    "tournaments.matchStatus.scheduled": "Đã lên lịch",
    "tournaments.matchStatus.ongoing": "Đang diễn ra",
    "tournaments.matchStatus.completed": "Hoàn thành",
    "tournaments.matchStatus.cancelled": "Đã hủy",
    "tournaments.registrationMobileDesc": "Đăng ký nhanh chóng qua ứng dụng di động hoặc trình duyệt",
    "tournaments.registrationWebDesc": "Đăng ký tham gia giải đấu trực tuyến",
    "tournaments.openRegistration": "Đang mở đăng ký",
    "tournaments.closedRegistration": "Đã đóng đăng ký",
    "tournaments.registrationOptions": "Tùy chọn đăng ký",
    "tournaments.registerInApp": "Đăng ký trong ứng dụng",
    "tournaments.recommendedMobile": "Được khuyến nghị cho mobile",
    "tournaments.registerInBrowser": "Đăng ký trong trình duyệt",
    "tournaments.alternativeOption": "Tùy chọn thay thế",
    "tournaments.registerNow": "Đăng ký ngay",
    "tournaments.quickWebRegistration": "Đăng ký nhanh trên web",
    "tournaments.mobileAppPromo": "Tải ứng dụng di động để có trải nghiệm tốt nhất!",
    "tournaments.downloadApp": "Tải ứng dụng",
    "tournaments.registrationClosed": "Đăng ký đã đóng",
    "tournaments.tournamentFull": "Giải đấu đã đầy",
    "tournaments.registrationDeadlinePassed": "Hết hạn đăng ký",
    "tournaments.free": "Miễn phí",
    "tournaments.viewVenue": "Xem địa điểm",
    "tournaments.registrationDeadline": "Hạn đăng ký",
    "tournaments.noRegistrationDeadline": "Không có hạn đăng ký",
    "tournaments.instantConfirmation": "Xác nhận ngay lập tức",

    // Featured Players
    "players.breadcrumb": "SABO ARENA",
    "players.topPlayers": "CƠ THỦ HÀNG ĐẦU",
    "players.reigningChampion": "Nhà Vô Địch Đương Nhiệm",
    "players.championDesc": "Nhà vô địch bất bại với hơn 500 chiến thắng giải đấu. Nổi tiếng với những cú đánh chính xác và chiến thuật bậc thầy. Hiện đang giữ kỷ lục thế giới về số trận thắng liên tiếp.",
    "players.tournamentWins": "Chiến Thắng",
    "players.winRate": "Tỷ Lệ Thắng",
    "players.championships": "Chức Vô Địch",
    "players.viewProfile": "Xem Hồ Sơ Đầy Đủ →",
    "players.watchHighlights": "Xem Điểm Nổi Bật →",
    "players.topRanked": "XẾP HẠNG",
    "players.topRankedFull": "CƠ THỦ",
    "players.eliteAthletes": "Gặp gỡ những cơ thủ xuất sắc thống trị đấu trường giải đấu",
    "players.professionalPlayer": "Cơ Thủ Chuyên Nghiệp",
    "players.tournaments": "Giải Đấu",
    "players.noPlayers": "Không tìm thấy cơ thủ nào",
    "players.totalPlayers": "Tổng Cơ Thủ",
    "players.rankTiers": "Hạng Thi Đấu",
    "players.totalTournaments": "Tổng Giải Đấu",
    "players.searchPlayers": "Tìm kiếm cơ thủ...",
    "players.allRanks": "Tất cả hạng",
    "players.sortByPoints": "Sắp xếp theo điểm",
    "players.sortByTournaments": "Sắp xếp theo giải đấu",
    "players.sortByWins": "Sắp xếp theo chiến thắng",
    "players.sortByElo": "Sắp xếp theo ELO",
    "players.noPlayersFound": "Không tìm thấy cơ thủ nào",
    "players.tryDifferentFilters": "Thử thay đổi bộ lọc tìm kiếm",
    "players.points": "Điểm",

    // Privacy Policy
    "privacy.title": "Chính Sách Quyền Riêng Tư",
    "privacy.lastUpdated": "Cập nhật lần cuối",
    "privacy.intro.title": "Giới Thiệu",
    "privacy.intro.content": "Chào mừng đến với SABO Arena. Chúng tôi tôn trọng quyền riêng tư của bạn và cam kết bảo vệ thông tin cá nhân. Chính sách này giải thích cách chúng tôi thu thập, sử dụng và bảo vệ dữ liệu của bạn khi sử dụng ứng dụng và nền tảng giải đấu bi-a của chúng tôi.",
    "privacy.collection.title": "Thông Tin Chúng Tôi Thu Thập",
    "privacy.collection.content": "Khi bạn đăng ký và sử dụng SABO Arena, chúng tôi thu thập:",
    "privacy.collection.email": "Địa chỉ email (từ Facebook/Google đăng nhập)",
    "privacy.collection.name": "Tên hiển thị",
    "privacy.collection.avatar": "Ảnh đại diện/Avatar",
    "privacy.collection.gameData": "Dữ liệu trò chơi (điểm số, kết quả thi đấu, thống kê)",
    "privacy.usage.title": "Cách Chúng Tôi Sử Dụng Thông Tin",
    "privacy.usage.content": "Thông tin của bạn được sử dụng cho:",
    "privacy.usage.tournaments": "Quản lý giải đấu và đăng ký tham gia",
    "privacy.usage.profiles": "Tạo và quản lý hồ sơ người dùng",
    "privacy.usage.leaderboards": "Hiển thị bảng xếp hạng và thành tích",
    "privacy.usage.communication": "Gửi thông báo về giải đấu và cập nhật",
    "privacy.storage.title": "Lưu Trữ Dữ Liệu",
    "privacy.storage.content": "Tất cả dữ liệu được lưu trữ an toàn trên cơ sở dữ liệu đám mây Supabase với mã hóa tiêu chuẩn ngành. Chúng tôi thực hiện các biện pháp bảo mật kỹ thuật và tổ chức phù hợp để bảo vệ thông tin của bạn khỏi truy cập, thay đổi hoặc tiết lộ trái phép.",
    "privacy.sharing.title": "Chia Sẻ Thông Tin",
    "privacy.sharing.content": "Chúng tôi KHÔNG chia sẻ thông tin cá nhân của bạn với bên thứ ba cho mục đích tiếp thị. Thông tin của bạn chỉ được chia sẻ khi cần thiết để vận hành dịch vụ hoặc theo yêu cầu của pháp luật.",
    "privacy.rights.title": "Quyền Của Bạn",
    "privacy.rights.content": "Bạn có quyền:",
    "privacy.rights.access": "Truy cập và xem thông tin cá nhân của bạn",
    "privacy.rights.correction": "Yêu cầu chỉnh sửa thông tin không chính xác",
    "privacy.rights.deletion": "Yêu cầu xóa dữ liệu cá nhân của bạn",
    "privacy.rights.export": "Xuất dữ liệu của bạn ở định dạng có thể đọc được",
    "privacy.security.title": "Bảo Mật",
    "privacy.security.content": "Chúng tôi sử dụng các biện pháp bảo mật tiêu chuẩn ngành bao gồm mã hóa SSL/TLS, xác thực an toàn và kiểm soát truy cập để bảo vệ dữ liệu của bạn. Tuy nhiên, không có phương thức truyền tải qua internet nào là 100% an toàn.",
    "privacy.children.title": "Quyền Riêng Tư Trẻ Em",
    "privacy.children.content": "Ứng dụng của chúng tôi không dành cho trẻ em dưới 13 tuổi. Chúng tôi không cố ý thu thập thông tin cá nhân từ trẻ em dưới 13 tuổi. Nếu bạn tin rằng chúng tôi có thông tin từ trẻ em dưới 13 tuổi, vui lòng liên hệ với chúng tôi.",
    "privacy.changes.title": "Thay Đổi Chính Sách",
    "privacy.changes.content": "Chúng tôi có thể cập nhật chính sách quyền riêng tư này theo thời gian. Chúng tôi sẽ thông báo cho bạn về bất kỳ thay đổi nào bằng cách đăng chính sách mới trên trang này và cập nhật ngày 'Cập nhật lần cuối'.",
    "privacy.contact.title": "Liên Hệ",
    "privacy.contact.content": "Nếu bạn có bất kỳ câu hỏi nào về Chính Sách Quyền Riêng Tư này hoặc muốn thực hiện quyền của mình, vui lòng liên hệ:",

    // Terms of Service
    "terms.title": "Điều Khoản Dịch Vụ",
    "terms.lastUpdated": "Cập nhật lần cuối",
    "terms.intro.title": "Chào Mừng Đến SABO Arena",
    "terms.intro.content": "Những Điều Khoản Dịch Vụ này quy định việc sử dụng nền tảng giải đấu bi-a SABO Arena. Bằng cách truy cập hoặc sử dụng dịch vụ của chúng tôi, bạn đồng ý bị ràng buộc bởi các điều khoản này.",
    "terms.acceptance.title": "Chấp Nhận Điều Khoản",
    "terms.acceptance.content": "Bằng cách tạo tài khoản hoặc sử dụng SABO Arena, bạn xác nhận rằng bạn đã đọc, hiểu và đồng ý tuân thủ các Điều Khoản Dịch Vụ này. Nếu bạn không đồng ý với bất kỳ phần nào của các điều khoản này, bạn không được sử dụng dịch vụ của chúng tôi.",
    "terms.account.title": "Tài Khoản Người Dùng",
    "terms.account.content": "Để sử dụng SABO Arena, bạn phải:",
    "terms.account.age": "Từ 13 tuổi trở lên",
    "terms.account.accurate": "Cung cấp thông tin chính xác và đầy đủ khi đăng ký",
    "terms.account.security": "Duy trì bảo mật tài khoản và mật khẩu của bạn",
    "terms.account.responsibility": "Chịu trách nhiệm cho tất cả hoạt động xảy ra dưới tài khoản của bạn",
    "terms.usage.title": "Điều Khoản Sử Dụng",
    "terms.usage.intro": "Khi sử dụng SABO Arena, bạn đồng ý:",
    "terms.usage.permitted.title": "Được Phép:",
    "terms.usage.permitted.tournaments": "Tham gia giải đấu và cuộc thi",
    "terms.usage.permitted.profile": "Tạo và duy trì hồ sơ người dùng",
    "terms.usage.permitted.compete": "Thi đấu một cách công bằng và có đạo đức",
    "terms.usage.permitted.interact": "Tương tác tích cực với cộng đồng",
    "terms.usage.prohibited.title": "Không Được Phép:",
    "terms.usage.prohibited.cheat": "Gian lận hoặc sử dụng phần mềm bất hợp pháp",
    "terms.usage.prohibited.harass": "Quấy rối, lạm dụng hoặc làm hại người dùng khác",
    "terms.usage.prohibited.impersonate": "Mạo danh người khác hoặc tổ chức",
    "terms.usage.prohibited.hack": "Cố gắng truy cập trái phép vào hệ thống",
    "terms.usage.prohibited.illegal": "Vi phạm bất kỳ luật hoặc quy định hiện hành",
    "terms.tournaments.title": "Quy Định Giải Đấu",
    "terms.tournaments.content": "Khi tham gia giải đấu trên SABO Arena:",
    "terms.tournaments.rules": "Bạn phải tuân thủ tất cả quy tắc và quy định giải đấu",
    "terms.tournaments.conduct": "Bạn phải duy trì hành vi thể thao và tôn trọng",
    "terms.tournaments.schedule": "Bạn phải tham dự các trận đấu theo lịch đã định",
    "terms.tournaments.decisions": "Quyết định của ban tổ chức là quyết định cuối cùng",
    "terms.payment.title": "Thanh Toán và Hoàn Tiền",
    "terms.payment.content": "Đối với giải đấu có phí tham gia:",
    "terms.payment.fees": "Tất cả phí phải được thanh toán trước khi đăng ký được xác nhận",
    "terms.payment.refund": "Hoàn tiền chỉ có sẵn theo chính sách hoàn tiền của từng giải đấu",
    "terms.payment.currency": "Giá được niêm yết bằng VND trừ khi có quy định khác",
    "terms.intellectual.title": "Sở Hữu Trí Tuệ",
    "terms.intellectual.content": "Tất cả nội dung, thương hiệu, logo và tài sản trí tuệ trên SABO Arena thuộc sở hữu của chúng tôi hoặc người cấp phép của chúng tôi. Bạn không được sử dụng, sao chép hoặc phân phối bất kỳ nội dung nào mà không có sự cho phép bằng văn bản.",
    "terms.liability.title": "Giới Hạn Trách Nhiệm",
    "terms.liability.content": "SABO Arena được cung cấp 'như hiện tại' mà không có bảo đảm nào. Chúng tôi không chịu trách nhiệm cho:",
    "terms.liability.availability": "Sự gián đoạn dịch vụ hoặc không khả dụng",
    "terms.liability.accuracy": "Sai sót hoặc thiếu sót trong nội dung",
    "terms.liability.thirdParty": "Hành động của người dùng bên thứ ba",
    "terms.liability.loss": "Mất mát hoặc thiệt hại phát sinh từ việc sử dụng dịch vụ",
    "terms.termination.title": "Chấm Dứt Tài Khoản",
    "terms.termination.content": "Chúng tôi có quyền đình chỉ hoặc chấm dứt tài khoản của bạn vào bất kỳ lúc nào vì vi phạm các điều khoản này hoặc hành vi bất hợp pháp. Bạn có thể chấm dứt tài khoản của mình bất kỳ lúc nào bằng cách liên hệ với chúng tôi.",
    "terms.changes.title": "Thay Đổi Điều Khoản",
    "terms.changes.content": "Chúng tôi có quyền sửa đổi các điều khoản này vào bất kỳ lúc nào. Thay đổi sẽ có hiệu lực ngay khi được đăng trên nền tảng. Việc tiếp tục sử dụng của bạn sau khi thay đổi có nghĩa là chấp nhận các điều khoản mới.",
    "terms.governing.title": "Luật Điều Chỉnh",
    "terms.governing.content": "Các Điều Khoản này được điều chỉnh bởi pháp luật Việt Nam. Bất kỳ tranh chấp nào phát sinh sẽ được giải quyết tại tòa án có thẩm quyền ở Việt Nam.",
    "terms.contact.title": "Liên Hệ",
    "terms.contact.content": "Nếu bạn có câu hỏi về Điều Khoản Dịch Vụ này, vui lòng liên hệ:",

    // Delete Account
    "deleteAccount.title": "Xóa Tài Khoản SABO Arena",
    "deleteAccount.subtitle": "Yêu cầu xóa tài khoản và dữ liệu cá nhân",
    "deleteAccount.warning": "Khi bạn xóa tài khoản, các dữ liệu sau sẽ bị xóa vĩnh viễn:",
    "deleteAccount.dataDeleted1": "Thông tin hồ sơ cá nhân (tên, email, avatar)",
    "deleteAccount.dataDeleted2": "Lịch sử tham gia giải đấu",
    "deleteAccount.dataDeleted3": "Thống kê và thành tích cá nhân",
    "deleteAccount.dataDeleted4": "Ảnh và nội dung đã tải lên",
    "deleteAccount.processingTime": "⏱️ Thời gian xử lý: 30 ngày làm việc",
    "deleteAccount.noRecovery": "⚠️ Không thể khôi phục sau khi đã xóa",
    "deleteAccount.emailLabel": "Địa chỉ Email",
    "deleteAccount.emailPlaceholder": "your.email@example.com",
    "deleteAccount.emailRequired": "Vui lòng nhập địa chỉ email hợp lệ",
    "deleteAccount.reasonLabel": "Lý do xóa tài khoản (không bắt buộc)",
    "deleteAccount.reasonPlaceholder": "Cho chúng tôi biết tại sao bạn muốn xóa tài khoản...",
    "deleteAccount.submitButton": "Gửi Yêu Cầu Xóa Tài Khoản",
    "deleteAccount.submitting": "Đang gửi...",
    "deleteAccount.confirmationTitle": "Yêu cầu đã được gửi!",
    "deleteAccount.confirmationMessage": "Chúng tôi đã nhận được yêu cầu xóa tài khoản của bạn. Dữ liệu sẽ được xử lý và xóa trong vòng 30 ngày làm việc. Bạn sẽ nhận được email xác nhận từ chúng tôi.",
    "deleteAccount.contactLabel": "Liên hệ:",
    "deleteAccount.successTitle": "Thành công",
    "deleteAccount.successMessage": "Yêu cầu xóa tài khoản đã được gửi thành công",
    "deleteAccount.error": "Lỗi",

    // Clubs
    "clubs.title": "CÂU LẠC BỘ",
    "clubs.directory": "Danh Sách",
    "clubs.venues": "Câu Lạc Bộ",
    "clubs.description": "Khám phá và kết nối với các câu lạc bộ bi-a hàng đầu trên khắp Việt Nam",
    "clubs.subtitle": "Khám phá những câu lạc bộ bi-a hàng đầu",
    "clubs.searchClubs": "Tìm kiếm câu lạc bộ...",
    "clubs.searchPlaceholder": "Tìm kiếm câu lạc bộ...",
    "clubs.filterLocation": "Lọc theo địa điểm",
    "clubs.allLocations": "Tất cả địa điểm",
    "clubs.filterRating": "Lọc theo đánh giá",
    "clubs.allRatings": "Tất cả đánh giá",
    "clubs.featured": "CÂU LẠC BỘ NỔI BẬT",
    "clubs.featuredDescription": "Những câu lạc bộ được đánh giá cao nhất",
    "clubs.noClubs": "Không tìm thấy câu lạc bộ nào",
    "clubs.noClubsFound": "Không tìm thấy câu lạc bộ nào",
    "clubs.tryDifferentFilters": "Thử thay đổi bộ lọc tìm kiếm",
    "clubs.rating": "Đánh giá",
    "clubs.tables": "bàn",
    "clubs.totalClubs": "Tổng câu lạc bộ",
    "clubs.totalTournaments": "Tổng giải đấu",
    "clubs.totalTables": "Tổng bàn chơi",
    "clubs.tournamentsHosted": "giải đấu đã tổ chức",
    "clubs.contact": "Liên hệ",
    "clubs.viewDetails": "Xem chi tiết",
    "clubs.sortByRating": "Sắp xếp theo đánh giá",
    "clubs.sortByTournaments": "Sắp xếp theo giải đấu",
    "clubs.sortByTables": "Sắp xếp theo số bàn",
    "clubs.sortByName": "Sắp xếp theo tên",

    // Authentication
    "auth.welcomeToSabo": "Chào mừng đến SABO Arena",
    "auth.signInToContinue": "Đăng nhập để tiếp tục",
    "auth.signIn": "Đăng Nhập",
    "auth.signUp": "Đăng Ký",
    "auth.email": "Email",
    "auth.emailPlaceholder": "your.email@example.com",
    "auth.password": "Mật khẩu",
    "auth.passwordPlaceholder": "Nhập mật khẩu",
    "auth.confirmPassword": "Xác nhận mật khẩu",
    "auth.confirmPasswordPlaceholder": "Nhập lại mật khẩu",
    "auth.fullName": "Họ và tên",
    "auth.fullNamePlaceholder": "Nhập họ và tên",
    "auth.signingIn": "Đang đăng nhập...",
    "auth.creatingAccount": "Đang tạo tài khoản...",
    "auth.createAccount": "Tạo tài khoản",
    "auth.orContinueWith": "Hoặc tiếp tục với",
    "auth.passwordMismatch": "Mật khẩu không khớp",
    "auth.passwordTooShort": "Mật khẩu phải có ít nhất 6 ký tự",
    "auth.signOut": "Đăng xuất",

    // Profile
    "profile.notFound": "Không tìm thấy hồ sơ",
    "profile.noName": "Chưa có tên",
    "profile.wins": "thắng",
    "profile.winRate": "tỷ lệ thắng",
    "profile.rank": "xếp hạng",
    "profile.points": "điểm",
    "profile.edit": "Chỉnh sửa",
    "profile.details": "Chi tiết",
    "profile.statistics": "Thống kê",
    "profile.history": "Lịch sử",
    "profile.personalInfo": "Thông tin cá nhân",
    "profile.editInfo": "Chỉnh sửa thông tin của bạn",
    "profile.viewInfo": "Xem thông tin cá nhân của bạn",
    "profile.fullName": "Họ và tên",
    "profile.fullNamePlaceholder": "Nhập họ và tên",
    "profile.phone": "Số điện thoại",
    "profile.phonePlaceholder": "Nhập số điện thoại",
    "profile.dateOfBirth": "Ngày sinh",
    "profile.skillLevel": "Trình độ",
    "profile.selectSkillLevel": "Chọn trình độ",
    "profile.beginner": "Người mới",
    "profile.intermediate": "Trung cấp",
    "profile.advanced": "Nâng cao",
    "profile.professional": "Chuyên nghiệp",
    "profile.bio": "Tiểu sử",
    "profile.bioPlaceholder": "Viết một chút về bản thân...",
    "profile.saving": "Đang lưu...",
    "profile.save": "Lưu",
    "profile.notProvided": "Chưa cung cấp",
    "profile.gameStatistics": "Thống kê trò chơi",
    "profile.totalTournaments": "Tổng giải đấu",
    "profile.currentRank": "Xếp hạng hiện tại",
    "profile.noStatsAvailable": "Chưa có thống kê",
    "profile.tournamentHistory": "Lịch sử giải đấu",
    "profile.historyComingSoon": "Lịch sử sẽ được cập nhật sớm",
    "profile.loadError": "Lỗi tải hồ sơ",
    "profile.saveError": "Lỗi lưu hồ sơ",

    // Common
    "common.close": "Đóng",
    "common.cancel": "Hủy",
    "common.goBack": "Quay lại",
  },
  en: {
    // Common
    "common.language": "en",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.backHome": "Back Home",
    "common.backToTournaments": "Back to Tournaments",
    "common.share": "Share",
    "common.availableOn": "Available on",
    "common.getItOn": "Get it on",
    
    // Navigation
    "nav.home": "HOME",
    "nav.tournaments": "TOURNAMENTS",
    "nav.rankings": "RANKINGS",
    "nav.players": "PLAYERS",
    "nav.clubs": "CLUBS",
    "nav.news": "NEWS",
    "nav.download": "DOWNLOAD APP",
    "nav.profile": "Profile",

    // App Download
    "app.getTheApp": "Get The App",
    "app.betterExperience": "Better mobile experience",
    "app.downloadTitle": "Download SABO Arena App",
    "app.downloadDescription": "Experience the ultimate billiard gaming with our mobile app. Quick tournament registration, real-time match notifications, and connect with the billiard community.",
    "app.feature1": "Register tournaments in 1 minute",
    "app.feature2": "Real-time match notifications",
    "app.feature3": "Chat with opponents and friends",

    // Footer
    "footer.description": "Vietnam's leading billiard tournament platform. Connect community, compete professionally, elevate your skills.",
    "footer.quickLinks": "Quick Links",
    "footer.support": "Support",
    "footer.contact": "Contact",
    "footer.liveMatches": "Live Matches",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.deleteAccount": "Delete Account",
    "footer.contactUs": "Contact Us",
    "footer.faq": "FAQ",
    "footer.address": "123 ABC Street, District 1, Ho Chi Minh City, Vietnam",
    "footer.allRightsReserved": "All rights reserved.",
    "footer.madeWith": "Made with",
    "footer.forBilliardCommunity": "for Vietnamese billiard community",

    // Hero Section
    "hero.championship": "Championship",
    "hero.title1": "LEVEL PLAY",
    "hero.title2": "AWAITS",
    "hero.title3": "YOU!",
    "hero.description": "Join the ultimate billiard championship platform. Compete with elite players, participate in prestigious tournaments, and master your game.",
    "hero.joinTournament": "REGISTER NOW",
    "hero.viewRankings": "VIEW RANKINGS",
    "hero.activePlayers": "Active Players",
    "hero.tournaments": "Tournaments",
    "hero.prizePool": "Prize Pool",
    "hero.scrollExplore": "Scroll to explore",

    // Hero Cards
    "hero.upcomingTournament": "Upcoming Tournament",
    "hero.proLeagueFinals": "Pro League Finals 2024",
    "hero.tournamentDesc": "Registration closes in 5 days. 64 players competing for $50,000 grand prize.",
    "hero.joinNow": "GET APP NOW",
    "hero.highlights": "Highlights",
    "hero.topShots": "Top Shots of the Week",
    "hero.topShotsDesc": "Watch the most incredible plays from this week's tournaments.",
    "hero.latestNews": "Latest News",
    "hero.championshipRules": "New Championship Rules Announced",
    "hero.rulesDesc": "Tournament organizers introduce updated scoring system for the 2024 season.",
    "hero.readMore": "READ MORE",

    // Tournaments
    "tournaments.upcoming": "UPCOMING TOURNAMENTS",
    "tournaments.upcomingDescription": "Join world-class tournaments with the best players globally",
    "tournaments.noUpcoming": "No upcoming tournaments at the moment",
    "tournaments.participants": "Participants",
    "tournaments.prize": "Prize Pool",
    "tournaments.entryFee": "Entry Fee", 
    "tournaments.register": "REGISTER",
    "tournaments.full": "FULL",
    "tournaments.viewAll": "VIEW ALL",
    "tournaments.notFound": "Tournament Not Found",
    "tournaments.notFoundDesc": "The tournament you're looking for doesn't exist or has been removed",
    "tournaments.overview": "Overview",
    "tournaments.bracket": "Bracket",
    "tournaments.matches": "Matches",
    "tournaments.participantsList": "Participants",
    "tournaments.about": "About",
    "tournaments.format": "Format",
    "tournaments.venue": "Venue",
    "tournaments.startDate": "Start Date",
    "tournaments.endDate": "End Date",
    "tournaments.description": "Description",
    "tournaments.rules": "Rules",
    "tournaments.rule1": "All matches must be completed within scheduled time",
    "tournaments.rule2": "Players must arrive on time according to schedule",
    "tournaments.rule3": "Referee's decision is final",
    "tournaments.tournamentBracket": "Tournament Bracket",
    "tournaments.bracketComingSoon": "Bracket will be updated soon",
    "tournaments.noBracket": "No bracket available yet",
    "tournaments.matchResults": "Match Results",
    "tournaments.noMatches": "No matches yet",
    "tournaments.tbd": "TBD",
    "tournaments.scheduled": "Scheduled",
    "tournaments.winner": "Winner",
    "tournaments.noParticipants": "No participants yet",
    "tournaments.registration": "Registration",
    "tournaments.spots": "Spots",
    "tournaments.organizer": "Organizer",
    "tournaments.quickStats": "Quick Stats",
    "tournaments.avgRating": "Avg Rating",
    "tournaments.topSeed": "Top Seed",
    "tournaments.totalPrize": "Total Prize",
    "tournaments.totalMatches": "Total Matches",
    "tournaments.prizePool": "Prize Pool",
    "tournaments.standard": "Standard",
    "tournaments.status.upcoming": "Upcoming",
    "tournaments.status.ongoing": "Ongoing",
    "tournaments.status.completed": "Completed",
    "tournaments.status.cancelled": "Cancelled",
    "tournaments.matchStatus.scheduled": "Scheduled",
    "tournaments.matchStatus.ongoing": "Ongoing",
    "tournaments.matchStatus.completed": "Completed",
    "tournaments.matchStatus.cancelled": "Cancelled",
    "tournaments.registrationMobileDesc": "Quick registration via mobile app or browser",
    "tournaments.registrationWebDesc": "Register for the tournament online",
    "tournaments.openRegistration": "Open Registration",
    "tournaments.closedRegistration": "Closed Registration",
    "tournaments.registrationOptions": "Registration Options",
    "tournaments.registerInApp": "Register in App",
    "tournaments.recommendedMobile": "Recommended for mobile",
    "tournaments.registerInBrowser": "Register in Browser",
    "tournaments.alternativeOption": "Alternative option",
    "tournaments.registerNow": "Register Now",
    "tournaments.quickWebRegistration": "Quick web registration",
    "tournaments.mobileAppPromo": "Download the mobile app for the best experience!",
    "tournaments.downloadApp": "Download App",
    "tournaments.registrationClosed": "Registration closed",
    "tournaments.tournamentFull": "Tournament full",
    "tournaments.registrationDeadlinePassed": "Registration deadline passed",
    "tournaments.free": "Free",
    "tournaments.viewVenue": "View Venue",
    "tournaments.registrationDeadline": "Registration deadline",
    "tournaments.noRegistrationDeadline": "No registration deadline",
    "tournaments.instantConfirmation": "Instant confirmation",

    // Featured Players
    "players.breadcrumb": "SABO ARENA",
    "players.topPlayers": "TOP PLAYERS",
    "players.reigningChampion": "Reigning Champion",
    "players.championDesc": "Undefeated champion with 500+ tournament wins. Known for precision shots and strategic mastery. Currently holding the world record for consecutive wins.",
    "players.tournamentWins": "Tournament Wins",
    "players.winRate": "Win Rate",
    "players.championships": "Championships",
    "players.viewProfile": "View Full Profile →",
    "players.watchHighlights": "Watch Highlights →",
    "players.topRanked": "TOP RANKED",
    "players.topRankedFull": "PLAYERS",
    "players.eliteAthletes": "Meet the elite athletes dominating the championship circuit",
    "players.professionalPlayer": "Professional Player",
    "players.tournaments": "Tournaments",
    "players.noPlayers": "No players found",
    "players.totalPlayers": "Total Players",
    "players.rankTiers": "Rank Tiers",
    "players.totalTournaments": "Total Tournaments",
    "players.searchPlayers": "Search players...",
    "players.allRanks": "All Ranks",
    "players.sortByPoints": "Sort by Points",
    "players.sortByTournaments": "Sort by Tournaments",
    "players.sortByWins": "Sort by Wins",
    "players.sortByElo": "Sort by ELO",
    "players.noPlayersFound": "No players found",
    "players.tryDifferentFilters": "Try different search filters",
    "players.points": "Points",

    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated",
    "privacy.intro.title": "Introduction",
    "privacy.intro.content": "Welcome to SABO Arena. We respect your privacy and are committed to protecting your personal information. This policy explains how we collect, use, and safeguard your data when using our billiards tournament platform and application.",
    "privacy.collection.title": "Information We Collect",
    "privacy.collection.content": "When you register and use SABO Arena, we collect:",
    "privacy.collection.email": "Email address (from Facebook/Google login)",
    "privacy.collection.name": "Display name",
    "privacy.collection.avatar": "Profile picture/Avatar",
    "privacy.collection.gameData": "Game data (scores, match results, statistics)",
    "privacy.usage.title": "How We Use Your Information",
    "privacy.usage.content": "Your information is used for:",
    "privacy.usage.tournaments": "Tournament management and registration",
    "privacy.usage.profiles": "Creating and managing user profiles",
    "privacy.usage.leaderboards": "Displaying leaderboards and achievements",
    "privacy.usage.communication": "Sending tournament notifications and updates",
    "privacy.storage.title": "Data Storage",
    "privacy.storage.content": "All data is securely stored on Supabase cloud database with industry-standard encryption. We implement appropriate technical and organizational security measures to protect your information from unauthorized access, alteration, or disclosure.",
    "privacy.sharing.title": "Information Sharing",
    "privacy.sharing.content": "We DO NOT share your personal information with third parties for marketing purposes. Your information is only shared when necessary to operate the service or as required by law.",
    "privacy.rights.title": "Your Rights",
    "privacy.rights.content": "You have the right to:",
    "privacy.rights.access": "Access and view your personal information",
    "privacy.rights.correction": "Request correction of inaccurate information",
    "privacy.rights.deletion": "Request deletion of your personal data",
    "privacy.rights.export": "Export your data in a readable format",
    "privacy.security.title": "Security",
    "privacy.security.content": "We use industry-standard security measures including SSL/TLS encryption, secure authentication, and access controls to protect your data. However, no method of transmission over the internet is 100% secure.",
    "privacy.children.title": "Children's Privacy",
    "privacy.children.content": "Our application is not intended for children under 13. We do not knowingly collect personal information from children under 13. If you believe we have information from a child under 13, please contact us.",
    "privacy.changes.title": "Policy Changes",
    "privacy.changes.content": "We may update this privacy policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the 'Last updated' date.",
    "privacy.contact.title": "Contact Us",
    "privacy.contact.content": "If you have any questions about this Privacy Policy or wish to exercise your rights, please contact:",

    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated",
    "terms.intro.title": "Welcome to SABO Arena",
    "terms.intro.content": "These Terms of Service govern your use of the SABO Arena billiards tournament platform. By accessing or using our services, you agree to be bound by these terms.",
    "terms.acceptance.title": "Acceptance of Terms",
    "terms.acceptance.content": "By creating an account or using SABO Arena, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services.",
    "terms.account.title": "User Accounts",
    "terms.account.content": "To use SABO Arena, you must:",
    "terms.account.age": "Be at least 13 years old",
    "terms.account.accurate": "Provide accurate and complete information when registering",
    "terms.account.security": "Maintain the security of your account and password",
    "terms.account.responsibility": "Accept responsibility for all activities that occur under your account",
    "terms.usage.title": "Acceptable Use",
    "terms.usage.intro": "When using SABO Arena, you agree to:",
    "terms.usage.permitted.title": "Permitted Use:",
    "terms.usage.permitted.tournaments": "Participate in tournaments and competitions",
    "terms.usage.permitted.profile": "Create and maintain user profiles",
    "terms.usage.permitted.compete": "Compete fairly and ethically",
    "terms.usage.permitted.interact": "Interact positively with the community",
    "terms.usage.prohibited.title": "Prohibited Conduct:",
    "terms.usage.prohibited.cheat": "Cheat or use unauthorized software",
    "terms.usage.prohibited.harass": "Harass, abuse, or harm other users",
    "terms.usage.prohibited.impersonate": "Impersonate others or organizations",
    "terms.usage.prohibited.hack": "Attempt unauthorized access to systems",
    "terms.usage.prohibited.illegal": "Violate any applicable laws or regulations",
    "terms.tournaments.title": "Tournament Rules",
    "terms.tournaments.content": "When participating in tournaments on SABO Arena:",
    "terms.tournaments.rules": "You must follow all tournament rules and regulations",
    "terms.tournaments.conduct": "You must maintain sportsmanlike conduct and respect",
    "terms.tournaments.schedule": "You must attend scheduled matches on time",
    "terms.tournaments.decisions": "Tournament organizer decisions are final",
    "terms.payment.title": "Payment and Refunds",
    "terms.payment.content": "For tournaments with entry fees:",
    "terms.payment.fees": "All fees must be paid before registration is confirmed",
    "terms.payment.refund": "Refunds are only available according to each tournament's refund policy",
    "terms.payment.currency": "Prices are listed in VND unless otherwise stated",
    "terms.intellectual.title": "Intellectual Property",
    "terms.intellectual.content": "All content, trademarks, logos, and intellectual property on SABO Arena are owned by us or our licensors. You may not use, copy, or distribute any content without written permission.",
    "terms.liability.title": "Limitation of Liability",
    "terms.liability.content": "SABO Arena is provided 'as is' without warranties. We are not liable for:",
    "terms.liability.availability": "Service interruptions or unavailability",
    "terms.liability.accuracy": "Errors or omissions in content",
    "terms.liability.thirdParty": "Actions of third-party users",
    "terms.liability.loss": "Loss or damages arising from service use",
    "terms.termination.title": "Account Termination",
    "terms.termination.content": "We reserve the right to suspend or terminate your account at any time for violation of these terms or illegal conduct. You may terminate your account at any time by contacting us.",
    "terms.changes.title": "Changes to Terms",
    "terms.changes.content": "We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting on the platform. Your continued use after changes constitutes acceptance of the new terms.",
    "terms.governing.title": "Governing Law",
    "terms.governing.content": "These Terms are governed by the laws of Vietnam. Any disputes arising shall be resolved in the competent courts of Vietnam.",
    "terms.contact.title": "Contact Us",
    "terms.contact.content": "If you have questions about these Terms of Service, please contact:",

    // Delete Account
    "deleteAccount.title": "Delete SABO Arena Account",
    "deleteAccount.subtitle": "Request account and personal data deletion",
    "deleteAccount.warning": "When you delete your account, the following data will be permanently deleted:",
    "deleteAccount.dataDeleted1": "Personal profile information (name, email, avatar)",
    "deleteAccount.dataDeleted2": "Tournament participation history",
    "deleteAccount.dataDeleted3": "Personal statistics and achievements",
    "deleteAccount.dataDeleted4": "Photos and uploaded content",
    "deleteAccount.processingTime": "⏱️ Processing time: 30 business days",
    "deleteAccount.noRecovery": "⚠️ Cannot be recovered after deletion",
    "deleteAccount.emailLabel": "Email Address",
    "deleteAccount.emailPlaceholder": "your.email@example.com",
    "deleteAccount.emailRequired": "Please enter a valid email address",
    "deleteAccount.reasonLabel": "Reason for deletion (optional)",
    "deleteAccount.reasonPlaceholder": "Let us know why you want to delete your account...",
    "deleteAccount.submitButton": "Submit Deletion Request",
    "deleteAccount.submitting": "Submitting...",
    "deleteAccount.confirmationTitle": "Request Submitted!",
    "deleteAccount.confirmationMessage": "We have received your account deletion request. Your data will be processed and deleted within 30 business days. You will receive a confirmation email from us.",
    "deleteAccount.contactLabel": "Contact:",
    "deleteAccount.successTitle": "Success",
    "deleteAccount.successMessage": "Account deletion request submitted successfully",
    "deleteAccount.error": "Error",

    // Clubs
    "clubs.title": "CLUBS",
    "clubs.directory": "Clubs",
    "clubs.venues": "Directory",
    "clubs.description": "Discover and connect with top billiard clubs across Vietnam",
    "clubs.subtitle": "Discover top-rated billiard clubs",
    "clubs.searchClubs": "Search clubs...",
    "clubs.searchPlaceholder": "Search clubs...",
    "clubs.filterLocation": "Filter by location",
    "clubs.allLocations": "All locations",
    "clubs.filterRating": "Filter by rating",
    "clubs.allRatings": "All ratings",
    "clubs.featured": "FEATURED CLUBS",
    "clubs.featuredDescription": "Top-rated clubs you should visit",
    "clubs.noClubs": "No clubs found",
    "clubs.noClubsFound": "No clubs found",
    "clubs.tryDifferentFilters": "Try different search filters",
    "clubs.rating": "Rating",
    "clubs.tables": "tables",
    "clubs.totalClubs": "Total Clubs",
    "clubs.totalTournaments": "Total Tournaments",
    "clubs.totalTables": "Total Tables",
    "clubs.tournamentsHosted": "tournaments hosted",
    "clubs.contact": "Contact",
    "clubs.viewDetails": "View Details",
    "clubs.sortByRating": "Sort by rating",
    "clubs.sortByTournaments": "Sort by tournaments",
    "clubs.sortByTables": "Sort by tables",
    "clubs.sortByName": "Sort by name",

    // Authentication
    "auth.welcomeToSabo": "Welcome to SABO Arena",
    "auth.signInToContinue": "Sign in to continue",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.emailPlaceholder": "your.email@example.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter password",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Re-enter password",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "Enter full name",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    "auth.createAccount": "Create Account",
    "auth.orContinueWith": "Or continue with",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters",
    "auth.signOut": "Sign Out",

    // Profile
    "profile.notFound": "Profile not found",
    "profile.noName": "No name",
    "profile.wins": "wins",
    "profile.winRate": "win rate",
    "profile.rank": "rank",
    "profile.points": "points",
    "profile.edit": "Edit",
    "profile.details": "Details",
    "profile.statistics": "Statistics",
    "profile.history": "History",
    "profile.personalInfo": "Personal Information",
    "profile.editInfo": "Edit your information",
    "profile.viewInfo": "View your personal information",
    "profile.fullName": "Full Name",
    "profile.fullNamePlaceholder": "Enter full name",
    "profile.phone": "Phone Number",
    "profile.phonePlaceholder": "Enter phone number",
    "profile.dateOfBirth": "Date of Birth",
    "profile.skillLevel": "Skill Level",
    "profile.selectSkillLevel": "Select skill level",
    "profile.beginner": "Beginner",
    "profile.intermediate": "Intermediate",
    "profile.advanced": "Advanced",
    "profile.professional": "Professional",
    "profile.bio": "Bio",
    "profile.bioPlaceholder": "Write a bit about yourself...",
    "profile.saving": "Saving...",
    "profile.save": "Save",
    "profile.notProvided": "Not provided",
    "profile.gameStatistics": "Game Statistics",
    "profile.totalTournaments": "Total Tournaments",
    "profile.currentRank": "Current Rank",
    "profile.noStatsAvailable": "No statistics available",
    "profile.tournamentHistory": "Tournament History",
    "profile.historyComingSoon": "History coming soon",
    "profile.loadError": "Error loading profile",
    "profile.saveError": "Error saving profile",

    // Common
    "common.close": "Close",
    "common.cancel": "Cancel",
    "common.goBack": "Go Back",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("vi"); // Vietnamese as default

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.vi] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
