import { createContext, useContext, useState, ReactNode } from "react";

type Language = "vi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  vi: {
    // Common
    "common.language": "vi",
    
    // Navigation
    "nav.home": "TRANG CHỦ",
    "nav.tournaments": "GIẢI ĐẤU",
    "nav.rankings": "BXH",
    "nav.players": "CƠ THỦ",
    "nav.clubs": "CÂU LẠC BỘ",
    "nav.news": "TIN TỨC",
    "nav.download": "TẢI ỨNG DỤNG",

    // Hero Section
    "hero.championship": "Giải Đấu",
    "hero.title1": "ĐẲNG CẤP",
    "hero.title2": "CHUYÊN NGHIỆP",
    "hero.title3": "CHỜ BẠN!",
    "hero.description": "Tham gia nền tảng giải đấu bi-a đẳng cấp. Thi đấu với những tay cơ xuất sắc, tham gia các giải đấu uy tín và nâng cao kỹ năng của bạn.",
    "hero.joinTournament": "THAM GIA GIẢI ĐẤU",
    "hero.viewRankings": "XEM BẢNG XẾP HẠNG",
    "hero.activePlayers": "Người Chơi",
    "hero.tournaments": "Giải Đấu",
    "hero.prizePool": "Giải Thưởng",
    "hero.scrollExplore": "Cuộn để khám phá",

    // Hero Cards
    "hero.upcomingTournament": "Giải Đấu Sắp Diễn Ra",
    "hero.proLeagueFinals": "Chung Kết Pro League 2024",
    "hero.tournamentDesc": "Đăng ký đóng trong 5 ngày. 64 người chơi tranh tài giải thưởng 50,000 USD.",
    "hero.joinNow": "ĐĂNG KÝ NGAY",
    "hero.highlights": "Điểm Nổi Bật",
    "hero.topShots": "Những Cú Đánh Đỉnh Cao Tuần Này",
    "hero.topShotsDesc": "Xem những pha bóng đỉnh cao nhất từ giải đấu tuần này.",
    "hero.latestNews": "Tin Mới Nhất",
    "hero.championshipRules": "Công Bố Quy Định Giải Đấu Mới",
    "hero.rulesDesc": "Ban tổ chức giải đấu giới thiệu hệ thống tính điểm cập nhật cho mùa giải 2024.",
    "hero.readMore": "ĐỌC THÊM",

    // Featured Players
    "players.breadcrumb": "SABO ARENA",
    "players.topPlayers": "CƠ THỦ HÀNG ĐẦU",
    "players.reigningChampion": "Nhà Vô Địch Đương Nhiệm",
    "players.championDesc": "Nhà vô địch bất bại với hơn 500 chiến thắng giải đấu. Nổi tiếng với những cú đánh chính xác và chiến thuật bậc thầy. Hiện đang giữ kỷ lục thế giới về số trận thắng liên tiếp.",
    "players.tournamentWins": "Chiến Thắng",
    "players.winRate": "Tỷ Lệ Thắng",
    "players.championships": "Chức Vô Địch",
    "players.viewProfile": "Xem Hồ Sơ Đầy Đủ →",
    "players.watchHighlights": "Xem Điểm Nổi Bật →",
    "players.topRanked": "XẾP HẠNG",
    "players.topRankedFull": "CƠ THỦ",
    "players.eliteAthletes": "Gặp gỡ những cơ thủ xuất sắc thống trị đấu trường giải đấu",
    "players.professionalPlayer": "Cơ Thủ Chuyên Nghiệp",
    "players.tournaments": "Giải Đấu",
    "players.noPlayers": "Không tìm thấy cơ thủ nào",

    // Privacy Policy
    "privacy.title": "Chính Sách Quyền Riêng Tư",
    "privacy.lastUpdated": "Cập nhật lần cuối",
    "privacy.intro.title": "Giới Thiệu",
    "privacy.intro.content": "Chào mừng đến với SABO Arena. Chúng tôi tôn trọng quyền riêng tư của bạn và cam kết bảo vệ thông tin cá nhân. Chính sách này giải thích cách chúng tôi thu thập, sử dụng và bảo vệ dữ liệu của bạn khi sử dụng ứng dụng và nền tảng giải đấu bi-a của chúng tôi.",
    "privacy.collection.title": "Thông Tin Chúng Tôi Thu Thập",
    "privacy.collection.content": "Khi bạn đăng ký và sử dụng SABO Arena, chúng tôi thu thập:",
    "privacy.collection.email": "Địa chỉ email (từ Facebook/Google đăng nhập)",
    "privacy.collection.name": "Tên hiển thị",
    "privacy.collection.avatar": "Ảnh đại diện/Avatar",
    "privacy.collection.gameData": "Dữ liệu trò chơi (điểm số, kết quả thi đấu, thống kê)",
    "privacy.usage.title": "Cách Chúng Tôi Sử Dụng Thông Tin",
    "privacy.usage.content": "Thông tin của bạn được sử dụng cho:",
    "privacy.usage.tournaments": "Quản lý giải đấu và đăng ký tham gia",
    "privacy.usage.profiles": "Tạo và quản lý hồ sơ người dùng",
    "privacy.usage.leaderboards": "Hiển thị bảng xếp hạng và thành tích",
    "privacy.usage.communication": "Gửi thông báo về giải đấu và cập nhật",
    "privacy.storage.title": "Lưu Trữ Dữ Liệu",
    "privacy.storage.content": "Tất cả dữ liệu được lưu trữ an toàn trên cơ sở dữ liệu đám mây Supabase với mã hóa tiêu chuẩn ngành. Chúng tôi thực hiện các biện pháp bảo mật kỹ thuật và tổ chức phù hợp để bảo vệ thông tin của bạn khỏi truy cập, thay đổi hoặc tiết lộ trái phép.",
    "privacy.sharing.title": "Chia Sẻ Thông Tin",
    "privacy.sharing.content": "Chúng tôi KHÔNG chia sẻ thông tin cá nhân của bạn với bên thứ ba cho mục đích tiếp thị. Thông tin của bạn chỉ được chia sẻ khi cần thiết để vận hành dịch vụ hoặc theo yêu cầu của pháp luật.",
    "privacy.rights.title": "Quyền Của Bạn",
    "privacy.rights.content": "Bạn có quyền:",
    "privacy.rights.access": "Truy cập và xem thông tin cá nhân của bạn",
    "privacy.rights.correction": "Yêu cầu chỉnh sửa thông tin không chính xác",
    "privacy.rights.deletion": "Yêu cầu xóa dữ liệu cá nhân của bạn",
    "privacy.rights.export": "Xuất dữ liệu của bạn ở định dạng có thể đọc được",
    "privacy.security.title": "Bảo Mật",
    "privacy.security.content": "Chúng tôi sử dụng các biện pháp bảo mật tiêu chuẩn ngành bao gồm mã hóa SSL/TLS, xác thực an toàn và kiểm soát truy cập để bảo vệ dữ liệu của bạn. Tuy nhiên, không có phương thức truyền tải qua internet nào là 100% an toàn.",
    "privacy.children.title": "Quyền Riêng Tư Trẻ Em",
    "privacy.children.content": "Ứng dụng của chúng tôi không dành cho trẻ em dưới 13 tuổi. Chúng tôi không cố ý thu thập thông tin cá nhân từ trẻ em dưới 13 tuổi. Nếu bạn tin rằng chúng tôi có thông tin từ trẻ em dưới 13 tuổi, vui lòng liên hệ với chúng tôi.",
    "privacy.changes.title": "Thay Đổi Chính Sách",
    "privacy.changes.content": "Chúng tôi có thể cập nhật chính sách quyền riêng tư này theo thời gian. Chúng tôi sẽ thông báo cho bạn về bất kỳ thay đổi nào bằng cách đăng chính sách mới trên trang này và cập nhật ngày 'Cập nhật lần cuối'.",
    "privacy.contact.title": "Liên Hệ",
    "privacy.contact.content": "Nếu bạn có bất kỳ câu hỏi nào về Chính Sách Quyền Riêng Tư này hoặc muốn thực hiện quyền của mình, vui lòng liên hệ:",

    // Terms of Service
    "terms.title": "Điều Khoản Dịch Vụ",
    "terms.lastUpdated": "Cập nhật lần cuối",
    "terms.intro.title": "Chào Mừng Đến SABO Arena",
    "terms.intro.content": "Những Điều Khoản Dịch Vụ này quy định việc sử dụng nền tảng giải đấu bi-a SABO Arena. Bằng cách truy cập hoặc sử dụng dịch vụ của chúng tôi, bạn đồng ý bị ràng buộc bởi các điều khoản này.",
    "terms.acceptance.title": "Chấp Nhận Điều Khoản",
    "terms.acceptance.content": "Bằng cách tạo tài khoản hoặc sử dụng SABO Arena, bạn xác nhận rằng bạn đã đọc, hiểu và đồng ý tuân thủ các Điều Khoản Dịch Vụ này. Nếu bạn không đồng ý với bất kỳ phần nào của các điều khoản này, bạn không được sử dụng dịch vụ của chúng tôi.",
    "terms.account.title": "Tài Khoản Người Dùng",
    "terms.account.content": "Để sử dụng SABO Arena, bạn phải:",
    "terms.account.age": "Từ 13 tuổi trở lên",
    "terms.account.accurate": "Cung cấp thông tin chính xác và đầy đủ khi đăng ký",
    "terms.account.security": "Duy trì bảo mật tài khoản và mật khẩu của bạn",
    "terms.account.responsibility": "Chịu trách nhiệm cho tất cả hoạt động xảy ra dưới tài khoản của bạn",
    "terms.usage.title": "Điều Khoản Sử Dụng",
    "terms.usage.intro": "Khi sử dụng SABO Arena, bạn đồng ý:",
    "terms.usage.permitted.title": "Được Phép:",
    "terms.usage.permitted.tournaments": "Tham gia giải đấu và cuộc thi",
    "terms.usage.permitted.profile": "Tạo và duy trì hồ sơ người dùng",
    "terms.usage.permitted.compete": "Thi đấu một cách công bằng và có đạo đức",
    "terms.usage.permitted.interact": "Tương tác tích cực với cộng đồng",
    "terms.usage.prohibited.title": "Không Được Phép:",
    "terms.usage.prohibited.cheat": "Gian lận hoặc sử dụng phần mềm bất hợp pháp",
    "terms.usage.prohibited.harass": "Quấy rối, lạm dụng hoặc làm hại người dùng khác",
    "terms.usage.prohibited.impersonate": "Mạo danh người khác hoặc tổ chức",
    "terms.usage.prohibited.hack": "Cố gắng truy cập trái phép vào hệ thống",
    "terms.usage.prohibited.illegal": "Vi phạm bất kỳ luật hoặc quy định hiện hành",
    "terms.tournaments.title": "Quy Định Giải Đấu",
    "terms.tournaments.content": "Khi tham gia giải đấu trên SABO Arena:",
    "terms.tournaments.rules": "Bạn phải tuân thủ tất cả quy tắc và quy định giải đấu",
    "terms.tournaments.conduct": "Bạn phải duy trì hành vi thể thao và tôn trọng",
    "terms.tournaments.schedule": "Bạn phải tham dự các trận đấu theo lịch đã định",
    "terms.tournaments.decisions": "Quyết định của ban tổ chức là quyết định cuối cùng",
    "terms.payment.title": "Thanh Toán và Hoàn Tiền",
    "terms.payment.content": "Đối với giải đấu có phí tham gia:",
    "terms.payment.fees": "Tất cả phí phải được thanh toán trước khi đăng ký được xác nhận",
    "terms.payment.refund": "Hoàn tiền chỉ có sẵn theo chính sách hoàn tiền của từng giải đấu",
    "terms.payment.currency": "Giá được niêm yết bằng VND trừ khi có quy định khác",
    "terms.intellectual.title": "Sở Hữu Trí Tuệ",
    "terms.intellectual.content": "Tất cả nội dung, thương hiệu, logo và tài sản trí tuệ trên SABO Arena thuộc sở hữu của chúng tôi hoặc người cấp phép của chúng tôi. Bạn không được sử dụng, sao chép hoặc phân phối bất kỳ nội dung nào mà không có sự cho phép bằng văn bản.",
    "terms.liability.title": "Giới Hạn Trách Nhiệm",
    "terms.liability.content": "SABO Arena được cung cấp 'như hiện tại' mà không có bảo đảm nào. Chúng tôi không chịu trách nhiệm cho:",
    "terms.liability.availability": "Sự gián đoạn dịch vụ hoặc không khả dụng",
    "terms.liability.accuracy": "Sai sót hoặc thiếu sót trong nội dung",
    "terms.liability.thirdParty": "Hành động của người dùng bên thứ ba",
    "terms.liability.loss": "Mất mát hoặc thiệt hại phát sinh từ việc sử dụng dịch vụ",
    "terms.termination.title": "Chấm Dứt Tài Khoản",
    "terms.termination.content": "Chúng tôi có quyền đình chỉ hoặc chấm dứt tài khoản của bạn vào bất kỳ lúc nào vì vi phạm các điều khoản này hoặc hành vi bất hợp pháp. Bạn có thể chấm dứt tài khoản của mình bất kỳ lúc nào bằng cách liên hệ với chúng tôi.",
    "terms.changes.title": "Thay Đổi Điều Khoản",
    "terms.changes.content": "Chúng tôi có quyền sửa đổi các điều khoản này vào bất kỳ lúc nào. Thay đổi sẽ có hiệu lực ngay khi được đăng trên nền tảng. Việc tiếp tục sử dụng của bạn sau khi thay đổi có nghĩa là chấp nhận các điều khoản mới.",
    "terms.governing.title": "Luật Điều Chỉnh",
    "terms.governing.content": "Các Điều Khoản này được điều chỉnh bởi pháp luật Việt Nam. Bất kỳ tranh chấp nào phát sinh sẽ được giải quyết tại tòa án có thẩm quyền ở Việt Nam.",
    "terms.contact.title": "Liên Hệ",
    "terms.contact.content": "Nếu bạn có câu hỏi về Điều Khoản Dịch Vụ này, vui lòng liên hệ:",

    // Delete Account
    "deleteAccount.title": "Xóa Tài Khoản SABO Arena",
    "deleteAccount.subtitle": "Yêu cầu xóa tài khoản và dữ liệu cá nhân",
    "deleteAccount.warning": "Khi bạn xóa tài khoản, các dữ liệu sau sẽ bị xóa vĩnh viễn:",
    "deleteAccount.dataDeleted1": "Thông tin hồ sơ cá nhân (tên, email, avatar)",
    "deleteAccount.dataDeleted2": "Lịch sử tham gia giải đấu",
    "deleteAccount.dataDeleted3": "Thống kê và thành tích cá nhân",
    "deleteAccount.dataDeleted4": "Ảnh và nội dung đã tải lên",
    "deleteAccount.processingTime": "⏱️ Thời gian xử lý: 30 ngày làm việc",
    "deleteAccount.noRecovery": "⚠️ Không thể khôi phục sau khi đã xóa",
    "deleteAccount.emailLabel": "Địa chỉ Email",
    "deleteAccount.emailPlaceholder": "your.email@example.com",
    "deleteAccount.emailRequired": "Vui lòng nhập địa chỉ email hợp lệ",
    "deleteAccount.reasonLabel": "Lý do xóa tài khoản (không bắt buộc)",
    "deleteAccount.reasonPlaceholder": "Cho chúng tôi biết tại sao bạn muốn xóa tài khoản...",
    "deleteAccount.submitButton": "Gửi Yêu Cầu Xóa Tài Khoản",
    "deleteAccount.submitting": "Đang gửi...",
    "deleteAccount.confirmationTitle": "Yêu cầu đã được gửi!",
    "deleteAccount.confirmationMessage": "Chúng tôi đã nhận được yêu cầu xóa tài khoản của bạn. Dữ liệu sẽ được xử lý và xóa trong vòng 30 ngày làm việc. Bạn sẽ nhận được email xác nhận từ chúng tôi.",
    "deleteAccount.contactLabel": "Liên hệ:",
    "deleteAccount.successTitle": "Thành công",
    "deleteAccount.successMessage": "Yêu cầu xóa tài khoản đã được gửi thành công",
    "deleteAccount.error": "Lỗi",
  },
  en: {
    // Common
    "common.language": "en",
    
    // Navigation
    "nav.home": "HOME",
    "nav.tournaments": "TOURNAMENTS",
    "nav.rankings": "RANKINGS",
    "nav.players": "PLAYERS",
    "nav.clubs": "CLUBS",
    "nav.news": "NEWS",
    "nav.download": "DOWNLOAD APP",

    // Hero Section
    "hero.championship": "Championship",
    "hero.title1": "LEVEL PLAY",
    "hero.title2": "AWAITS",
    "hero.title3": "YOU!",
    "hero.description": "Join the ultimate billiard championship platform. Compete with elite players, participate in prestigious tournaments, and master your game.",
    "hero.joinTournament": "JOIN TOURNAMENT",
    "hero.viewRankings": "VIEW RANKINGS",
    "hero.activePlayers": "Active Players",
    "hero.tournaments": "Tournaments",
    "hero.prizePool": "Prize Pool",
    "hero.scrollExplore": "Scroll to explore",

    // Hero Cards
    "hero.upcomingTournament": "Upcoming Tournament",
    "hero.proLeagueFinals": "Pro League Finals 2024",
    "hero.tournamentDesc": "Registration closes in 5 days. 64 players competing for $50,000 grand prize.",
    "hero.joinNow": "JOIN NOW",
    "hero.highlights": "Highlights",
    "hero.topShots": "Top Shots of the Week",
    "hero.topShotsDesc": "Watch the most incredible plays from this week's tournaments.",
    "hero.latestNews": "Latest News",
    "hero.championshipRules": "New Championship Rules Announced",
    "hero.rulesDesc": "Tournament committee introduces updated scoring system for 2024 season.",
    "hero.readMore": "READ MORE",

    // Featured Players
    "players.breadcrumb": "SABO ARENA",
    "players.topPlayers": "TOP PLAYERS",
    "players.reigningChampion": "Reigning Champion",
    "players.championDesc": "Undefeated champion with 500+ tournament wins. Known for precision shots and strategic mastery. Currently holding the world record for consecutive wins.",
    "players.tournamentWins": "Tournament Wins",
    "players.winRate": "Win Rate",
    "players.championships": "Championships",
    "players.viewProfile": "View Full Profile →",
    "players.watchHighlights": "Watch Highlights →",
    "players.topRanked": "TOP RANKED",
    "players.topRankedFull": "PLAYERS",
    "players.eliteAthletes": "Meet the elite athletes dominating the championship circuit",
    "players.professionalPlayer": "Professional Player",
    "players.tournaments": "Tournaments",
    "players.noPlayers": "No players found",

    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated",
    "privacy.intro.title": "Introduction",
    "privacy.intro.content": "Welcome to SABO Arena. We respect your privacy and are committed to protecting your personal information. This policy explains how we collect, use, and safeguard your data when using our billiards tournament platform and application.",
    "privacy.collection.title": "Information We Collect",
    "privacy.collection.content": "When you register and use SABO Arena, we collect:",
    "privacy.collection.email": "Email address (from Facebook/Google login)",
    "privacy.collection.name": "Display name",
    "privacy.collection.avatar": "Profile picture/Avatar",
    "privacy.collection.gameData": "Game data (scores, match results, statistics)",
    "privacy.usage.title": "How We Use Your Information",
    "privacy.usage.content": "Your information is used for:",
    "privacy.usage.tournaments": "Tournament management and registration",
    "privacy.usage.profiles": "Creating and managing user profiles",
    "privacy.usage.leaderboards": "Displaying leaderboards and achievements",
    "privacy.usage.communication": "Sending tournament notifications and updates",
    "privacy.storage.title": "Data Storage",
    "privacy.storage.content": "All data is securely stored on Supabase cloud database with industry-standard encryption. We implement appropriate technical and organizational security measures to protect your information from unauthorized access, alteration, or disclosure.",
    "privacy.sharing.title": "Information Sharing",
    "privacy.sharing.content": "We DO NOT share your personal information with third parties for marketing purposes. Your information is only shared when necessary to operate the service or as required by law.",
    "privacy.rights.title": "Your Rights",
    "privacy.rights.content": "You have the right to:",
    "privacy.rights.access": "Access and view your personal information",
    "privacy.rights.correction": "Request correction of inaccurate information",
    "privacy.rights.deletion": "Request deletion of your personal data",
    "privacy.rights.export": "Export your data in a readable format",
    "privacy.security.title": "Security",
    "privacy.security.content": "We use industry-standard security measures including SSL/TLS encryption, secure authentication, and access controls to protect your data. However, no method of transmission over the internet is 100% secure.",
    "privacy.children.title": "Children's Privacy",
    "privacy.children.content": "Our application is not intended for children under 13. We do not knowingly collect personal information from children under 13. If you believe we have information from a child under 13, please contact us.",
    "privacy.changes.title": "Policy Changes",
    "privacy.changes.content": "We may update this privacy policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the 'Last updated' date.",
    "privacy.contact.title": "Contact Us",
    "privacy.contact.content": "If you have any questions about this Privacy Policy or wish to exercise your rights, please contact:",

    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated",
    "terms.intro.title": "Welcome to SABO Arena",
    "terms.intro.content": "These Terms of Service govern your use of the SABO Arena billiards tournament platform. By accessing or using our services, you agree to be bound by these terms.",
    "terms.acceptance.title": "Acceptance of Terms",
    "terms.acceptance.content": "By creating an account or using SABO Arena, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services.",
    "terms.account.title": "User Accounts",
    "terms.account.content": "To use SABO Arena, you must:",
    "terms.account.age": "Be at least 13 years old",
    "terms.account.accurate": "Provide accurate and complete information when registering",
    "terms.account.security": "Maintain the security of your account and password",
    "terms.account.responsibility": "Accept responsibility for all activities that occur under your account",
    "terms.usage.title": "Acceptable Use",
    "terms.usage.intro": "When using SABO Arena, you agree to:",
    "terms.usage.permitted.title": "Permitted Use:",
    "terms.usage.permitted.tournaments": "Participate in tournaments and competitions",
    "terms.usage.permitted.profile": "Create and maintain user profiles",
    "terms.usage.permitted.compete": "Compete fairly and ethically",
    "terms.usage.permitted.interact": "Interact positively with the community",
    "terms.usage.prohibited.title": "Prohibited Conduct:",
    "terms.usage.prohibited.cheat": "Cheat or use unauthorized software",
    "terms.usage.prohibited.harass": "Harass, abuse, or harm other users",
    "terms.usage.prohibited.impersonate": "Impersonate others or organizations",
    "terms.usage.prohibited.hack": "Attempt unauthorized access to systems",
    "terms.usage.prohibited.illegal": "Violate any applicable laws or regulations",
    "terms.tournaments.title": "Tournament Rules",
    "terms.tournaments.content": "When participating in tournaments on SABO Arena:",
    "terms.tournaments.rules": "You must follow all tournament rules and regulations",
    "terms.tournaments.conduct": "You must maintain sportsmanlike conduct and respect",
    "terms.tournaments.schedule": "You must attend scheduled matches on time",
    "terms.tournaments.decisions": "Tournament organizer decisions are final",
    "terms.payment.title": "Payment and Refunds",
    "terms.payment.content": "For tournaments with entry fees:",
    "terms.payment.fees": "All fees must be paid before registration is confirmed",
    "terms.payment.refund": "Refunds are only available according to each tournament's refund policy",
    "terms.payment.currency": "Prices are listed in VND unless otherwise stated",
    "terms.intellectual.title": "Intellectual Property",
    "terms.intellectual.content": "All content, trademarks, logos, and intellectual property on SABO Arena are owned by us or our licensors. You may not use, copy, or distribute any content without written permission.",
    "terms.liability.title": "Limitation of Liability",
    "terms.liability.content": "SABO Arena is provided 'as is' without warranties. We are not liable for:",
    "terms.liability.availability": "Service interruptions or unavailability",
    "terms.liability.accuracy": "Errors or omissions in content",
    "terms.liability.thirdParty": "Actions of third-party users",
    "terms.liability.loss": "Loss or damages arising from service use",
    "terms.termination.title": "Account Termination",
    "terms.termination.content": "We reserve the right to suspend or terminate your account at any time for violation of these terms or illegal conduct. You may terminate your account at any time by contacting us.",
    "terms.changes.title": "Changes to Terms",
    "terms.changes.content": "We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting on the platform. Your continued use after changes constitutes acceptance of the new terms.",
    "terms.governing.title": "Governing Law",
    "terms.governing.content": "These Terms are governed by the laws of Vietnam. Any disputes arising shall be resolved in the competent courts of Vietnam.",
    "terms.contact.title": "Contact Us",
    "terms.contact.content": "If you have questions about these Terms of Service, please contact:",

    // Delete Account
    "deleteAccount.title": "Delete SABO Arena Account",
    "deleteAccount.subtitle": "Request account and personal data deletion",
    "deleteAccount.warning": "When you delete your account, the following data will be permanently deleted:",
    "deleteAccount.dataDeleted1": "Personal profile information (name, email, avatar)",
    "deleteAccount.dataDeleted2": "Tournament participation history",
    "deleteAccount.dataDeleted3": "Personal statistics and achievements",
    "deleteAccount.dataDeleted4": "Photos and uploaded content",
    "deleteAccount.processingTime": "⏱️ Processing time: 30 business days",
    "deleteAccount.noRecovery": "⚠️ Cannot be recovered after deletion",
    "deleteAccount.emailLabel": "Email Address",
    "deleteAccount.emailPlaceholder": "your.email@example.com",
    "deleteAccount.emailRequired": "Please enter a valid email address",
    "deleteAccount.reasonLabel": "Reason for deletion (optional)",
    "deleteAccount.reasonPlaceholder": "Let us know why you want to delete your account...",
    "deleteAccount.submitButton": "Submit Deletion Request",
    "deleteAccount.submitting": "Submitting...",
    "deleteAccount.confirmationTitle": "Request Submitted!",
    "deleteAccount.confirmationMessage": "We have received your account deletion request. Your data will be processed and deleted within 30 business days. You will receive a confirmation email from us.",
    "deleteAccount.contactLabel": "Contact:",
    "deleteAccount.successTitle": "Success",
    "deleteAccount.successMessage": "Account deletion request submitted successfully",
    "deleteAccount.error": "Error",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("vi"); // Vietnamese as default

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.vi] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
